auctions/urls.py
from django.contrib import admin 
from django.urls import path 
from django.conf import settings 
from django.conf.urls.static import static

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("item/<int:item_id>", views.item, name="item"),
    path("createlisting", views.createListing, name="create"),
    path("comment/<int:item_id>", views.comment, name="comment"),
    path("myitems", views.myitems, name="myitems"),
    path("delete/<int:item_id>", views.delete, name="delete"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("add/<int:item_id>", views.addtowatchlist, name="addtowatchlist"),
    path("remove/<int:item_id>", views.removefromwatchlist, name="removefromwatchlist"),
    path("category/<str:name>", views.category, name="category"),
    path("close/<int:item_id>", views.close, name="close")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Category(models.Model):
    category = models.CharField(max_length=64)

class Listing(models.Model):
    title = models.CharField(max_length=64)
    details = models.CharField(max_length=1500)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="myitems")
    display = models.ImageField(upload_to="images/")
    minbid = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="subitems")
    created_on = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)
    is_open = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.id}:{ self.title }"

class Comment(models.Model):
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="related")
    comment = models.CharField(max_length=240)
    created_on = models.DateTimeField(auto_now_add=True)

class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    bid = models.IntegerField(blank = True)
    created_on = models.DateTimeField(auto_now_add=True)

class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Listing)

auctions/forms.py
from django import forms

class BidForm(forms.Form):
    bid = forms.IntegerField(label="Your Bid ")

class LoginForm(forms.Form):
    username = forms.CharField(label="Username ", widget=forms.TextInput(
        attrs={
            "class": 'form-control'
        }
    ))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(
        attrs={
            "class": 'form-control'
        }
    ))
    
class RegisterForm(forms.Form):
    username = forms.CharField(label="Username", widget=forms.TextInput(
        attrs={
            "class": 'form-control'
        }
    ))
    email = forms.CharField(label="Email", widget=forms.EmailInput(
        attrs={
            "class": 'form-control'
        }
    ))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(
        attrs={
            "class": 'form-control'
        }
    ))
    confirmation = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(
        attrs={
            "class": 'form-control'
        }
    ))

class CreateForm(forms.Form):
    title = forms.CharField(label="Title ", widget=forms.TextInput(
        attrs={
            "class": 'form-control'
        }
    )) 
    category = forms.ChoiceField(label="Category ",choices=(
        ("Antiques","Antiques"),
        ("Books","Books"),
        ("Crafts","Crafts"),
        ("Electronics","Electronics"),
        ("Jewellery","Jewellery"),
        ("Paintings", "Paintings")
    ), widget=forms.Select(
        attrs={
            "class": 'form-control'
        }
    )) 
    details = forms.CharField(label="Description ", widget=forms.Textarea(
        attrs={
            "class": 'form-control'
        }
    ))
    display = forms.ImageField(label="Upload a picture ", widget=forms.ClearableFileInput(
        attrs={
            "class": 'form-control-file'
        }
    ))
    minbid = forms.IntegerField(label="Starting Bid (₹) ", widget=forms.NumberInput(
        attrs={
            "class": 'form-control'
        }
    ))

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import *
from .checks import *
from .forms import *

# Landing page. Shows active listings regardless of loggedin/loggedout
def index(request):
    return render(request, "auctions/index.html", {
        "items": Listing.objects.all(),
        "title": 'Active Listings'
    })


# Login page. Redirects to previous page using 'next' parameter
def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            # Attempt to sign user in
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(request, username=username, password=password)

            # Check if authentication successful
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(redirect_to=request.GET['next'] or reverse("auctions:index"))
            else:
                return render(request, "auctions/login.html", {
                    "message": "Invalid username and/or password.",
                    "form": form
                })
    else:
        form = LoginForm()
        return render(request, "auctions/login.html", {
            "form": form
        })


# Log out page. Redirects to landing page after log out.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


# Registration page for creating new users, also creates a field in Watchlist for them.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            email = request.POST["email"]

            # Ensure password matches confirmation
            password = request.POST["password"]
            confirmation = request.POST["confirmation"]
            if password != confirmation:
                return render(request, "auctions/register.html", {
                    "message": "Passwords must match."
                })

            # Attempt to create new user
            try:
                user = User.objects.create_user(username, email, password)
                user.save()
            except IntegrityError:
                return render(request, "auctions/register.html", {
                    "message": "Username already taken.",
                    "form": form
                })
            login(request, user)
            watch = Watchlist(user=user)
            watch.save()
            return HttpResponseRedirect(reverse("auctions:index"))
    else:
        form = RegisterForm()
        return render(request, "auctions/register.html", {
            "form": form
        })


# Shows individual item and various details like bids, comments included
@login_required
def item(request, item_id):
    item = Listing.objects.get(pk=item_id)
    check = checkauthor(item_id, request.user.id)
    if request.method == 'POST':
        form = BidForm(request.POST)
        if form.is_valid():
            bid_check = checkbid(item_id, request.POST['bid'])
            if bid_check == True:
                bid = Bid(bidder=User.objects.get(pk=request.user.id), item=item, bid=request.POST['bid'])
                bid.save()
                return redirect(reverse('auctions:item', args=(item_id,)))
            else:
                return render(request, "auctions/item.html", {
                    "item": item,
                    "bids": item.bids.all().order_by('-bid'),
                    "comments": item.related.all(),
                    "message": "Your bid must be greater than current and minimum bid.",
                    "check": check,
                    "form": form,
                    "there": checkwatchlist(request.user.id, item.id)
                })
    else:
        form = BidForm()
        return render(request, "auctions/item.html", {
            "item": item,
            "bids": item.bids.all().order_by('-bid'),
            "comments": item.related.all(),
            "check": check,
            "form": form,
            "there": checkwatchlist(request.user.id, item.id)
        })


# Page to create new listing
@login_required
def createListing(request):
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            listing = Listing(title=form.cleaned_data.get('title'), category=Category.objects.get(category=form.cleaned_data.get('category')), details=form.cleaned_data.get('details'),display=form.cleaned_data.get('display'), minbid=form.cleaned_data.get('minbid'), author=User.objects.get(pk=request.user.id))
            listing.save()
            return redirect(reverse('auctions:myitems'))
    else:
        form = CreateForm()
        return render(request, "auctions/createlisting.html", {
            "form": form
        })


# Updates new comments
@login_required
def comment(request, item_id):
    if request.method == 'POST':
        comment = Comment(commenter=User.objects.get(pk=request.user.id), item=Listing.objects.get(pk=item_id), comment=request.POST['comment'])
        comment.save()
    return redirect(reverse('auctions:item', args=(item_id,)))


# Page to show author of their listings
@login_required
def myitems(request):
    return render(request, "auctions/index.html", {
        "items": User.objects.get(pk=request.user.id).myitems.all(),
        "title": 'My Listings'
    })


# Method to delete a listing, accepts a post request if confirmed 'yes'
@login_required
def delete(request, item_id):
    if request.method == 'POST':
        Listing.objects.filter(pk=item_id).delete()
        return redirect(reverse('auctions:myitems'))
    return render(request, "auctions/delete.html", {
        "title": 'Are you sure you want to delete?',
        "item_id": item_id
    })


# Page to show listings added to watchlist
@login_required
def watchlist(request):
    return render(request, "auctions/index.html", {
        "title": 'Watchlist',
        "items": Watchlist.objects.get(user=User.objects.get(pk=request.user.id)).items.all()
    })

# Method to add item to watchlist
@login_required
def addtowatchlist(request, item_id):
    item = Watchlist.objects.get(user=User.objects.get(pk=request.user.id))
    item.items.add(Listing.objects.get(pk=item_id))
    return redirect(reverse('auctions:item', args=(item_id,)))


# Method to remove item from watchlist
@login_required
def removefromwatchlist(request, item_id):
    item = Watchlist.objects.get(user=User.objects.get(pk=request.user.id))
    item.items.remove(Listing.objects.get(pk=item_id))
    return redirect(reverse('auctions:item', args=(item_id,)))


# Page to show items of particular category
@login_required
def category(request, name):
    name = name.title()
    items = Category.objects.get(category=name).subitems.all()
    return render(request, "auctions/index.html", {
        "items": items,
        "title": name.title()
    })

@login_required
def close(request, item_id):
    try:
        bid = item.bids.all().order_by('-bid')[0]
        item = Listing.objects.get(pk=item_id)
        item.is_open = False
        item.save()
        return render(request, "auctions/close.html", {
            "bid": bid
        })
    except:
        return redirect(reverse("auctions:item", args=(item_id,)))

auctions/templates/auctions/close.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block body %}

<div class="container-fluid">
    <h1>Bidding Closed</h1>
    <h4>User {{ bid.bidder }} has won the item with a winning bid of {{ bid.bid }}.</h4>

    <a class="btn btn-primary" href="{% url 'auctions:index' %}">Go back to Active Listings</a>
</div>

{% endblock %}

auctions/templates/auctions/createlisting.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container-fluid">
    <h2> Create a Listing </h2><br>
    <div class="alert alert-warning" role="alert">
        Note: Your listing will show up only after the admin approves.
    </div>
    <form action="{% url 'auctions:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.title.label }}{{ form.title }}
        </div>
        <div class="form-group">
            {{ form.category.label }}{{ form.category }}
        </div>
        <div class="form-group">
            {{ form.details.label }}{{ form.details }}
        </div>
        <div class="form-group">
            {{ form.display.label }}{{ form.display }}
        </div>
        <div class="form-group">
            {{ form.minbid.label }}{{ form.minbid }}
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-2">Create</button>
        </div>
    </form>
</div>

{% endblock %}

auctions/templates/auctions/delete.html
{% extends "auctions/layout.html" %}

{% block body %}

    {% if title %}
    <h2>{{ title }}</h2>
    {% else %}
    <h2>Title</h2>
    {% endif %}
    <br>
    
    <div class="row">
        <div class="col-sm-3">
            <h3>Confirm </h3>
            <form action="{% url 'auctions:delete' item_id %}" method="POST">
                {% csrf_token %}
                <input class="btn btn-sm btn-primary" type="submit" value="Yes">
                <a class="btn btn-sm btn-primary" type="button" href="{% url 'auctions:item' item_id %}">No</a>
            </form>
        </div>
    </div>
    

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% load static %}
{% block body %}

    {% if title %}
    <h2>{{ title }}</h2>
    {% else %}
    <h2>Title</h2>
    {% endif %}
    <br>
    
    <div class="row">
        {% if message %}
        <div class="col-sm-3">
            <p>{{ message }}</p>
        </div>
        {% else %}
            {% for item in items %}
                {% if item.is_approved %}
                    {% if item.is_open %}
                        <div class="col-sm-3">
                            <div class="card" style="width: 18rem; margin: 10px;">
                                <img src="{{ item.display.url }}" class="card-img-top" alt="..." style="max-width: 18rem; max-height: 18rem;">
                                <div class="card-body">
                                <h5 class="card-title">{{ item.title }}</h5>
                                <p class="card-text"> {{ item.details }} </p>
                                <a href="{% url 'auctions:item' item.id %}" class="btn btn-primary">Peruse</a>
                                </div>
                            </div> 
                        </div>
                    {% endif %}
                {% endif %}
            {% empty %}
            <div class="container-fluid">
                <p>No listings yet.</p>
            </div>
            {% endfor %}
        {% endif %}
    </div>
    

{% endblock %}

auctions/templates/auctions/item.html
{% extends "auctions/layout.html" %}

{% load static %}
{% load tz %}
{% block body %}

<!--Info and enter bid-->
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <div class="card mb-4" style="width: 40rem; margin: 10px;">
                <img src="{{ item.display.url }}" class="p-2 rounded float-left" alt="..." style="min-height: 30rem; background-image: cover;">
                <div class="card-body pull-right">
                        <h3 class="p-2"> {{ item.title }} </h3>
                        <h6 class="p-2"> Listed by {{ item.author }} </h6>
                        <p class="p-2"> {{ item.created_on | localtime }} </p>
                        <p class="p-2"> Description: {{ item.details }} </p>
                        <p class="p-2"> Category: {{ item.category.category }}</p>
                        <h6 class="p-2"> Minimum bid: ₹{{ item.minbid }} </h6>
                        
                        <!--Bid form-->
                        {% if check %}
                        <a class="btn btn-sm btn-primary" href="{% url 'auctions:close' item.id %}">Close Bidding</a>
                        <div class="alert alert-warning" role="alert">
                            Warning: You can't close listings without bids.
                        </div>
                        {% else %}
                        <form class="p-2" action="{% url 'auctions:item' item.id %}" method="POST" >
                                {% csrf_token %}
                                <div class="form-row align-items-center">
                                    <div class="col-auto">
                                        {{ form.bid.label }} {{ form.bid }}
                                    </div>
                                    <div class="col-auto">
                                        <button type="submit" class="btn btn-primary btn-sm">Bid</button>
                                    </div>
                                </div>
                                <p>{{ message }}</p>
                        </form><br>
                        
                        <!--Add to Watchlist-->
                            {% if there %}
                            <a class="btn btn-primary btn-small" href="{% url 'auctions:removefromwatchlist' item.id %}">Remove from Watchlist</a>
                            {% else %}
                            <a class="btn btn-primary btn-small" href="{% url 'auctions:addtowatchlist' item.id %}">Add to Watchlist</a>
                            {% endif %}
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>



<!--Current Bids Section-->
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <h2>Current Bids</h2>
            {% for bid in bids %}
            <div class="p-3 bg-white mt-2 rounded">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row user"><img class="rounded-circle img-fluid img-responsive" src="{% static 'auctions/thumbnail.png' %}" width="40">
                        <div class="d-flex flex-column ml-2"><span class="font-weight-bold">{{ bid.bidder }}</span><span class="day">{{ bid.created_on }}</span></div>
                    </div>
                    <div class="d-flex align-items-center px-3 heart border"><i class="fa fa-heart-o heart-icon"></i><span class="ml-2">₹{{ bid.bid }}</span></div>
                </div>
            </div>
            {% empty %}
            <p>No bids yet.</p>
            {% endfor %}
            
        </div>
    </div>
</div>

<!--Comment section-->
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <h2>Comments</h2>

            {% for comment in comments %}
            <div class="p-3 bg-white mt-2 rounded">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row user"><img class="rounded-circle img-fluid img-responsive" src="{% static 'auctions/thumbnail.png' %}" alt="" width="40">
                        <div class="d-flex flex-column ml-2"><span class="font-weight-bold">{{ comment.commenter }}</span><span class="day">{{ comment.created_on }}</span></div>
                    </div>
                    <!--<div class="d-flex align-items-center px-3 heart border"><i class="fa fa-heart-o heart-icon"></i><span class="ml-2">35</span></div>-->
                </div>
                <div class="comment-text text-justify mt-2">
                    <p>{{ comment.comment }}</p>
                </div>
                <!--<div class="d-flex justify-content-end align-items-center comment-buttons mt-2 text-right">
                    <span class="mr-3 delete">Delete</span>
                    <button class="btn btn-success btn-sm border-0 px-3" type="button">Edit</button>
                </div>-->
            </div>
            {% empty %}
            <p>No comments yet.</p>
            {% endfor %}

            <div class="p-3 bg-white mt-2 rounded">
                <form action="{% url 'auctions:comment' item.id %}" method="POST">
                    {% csrf_token %}
                    <div class="comment-text text-justify mt-2">
                        <div class="d-flex flex-row user">
                            <img class="rounded-circle img-fluid img-responsive" src="{% static 'auctions/thumbnail.png' %}" width="40">
                        </div>
                        <input name="comment" type="text" class="form-control border-0 no-box-shadow ml-1" placeholder="Leave a comment..." required>
                    </div>
                    <div class="d-flex justify-content-end align-items-center comment-buttons mt-2 text-right">
                        <button class="btn btn-success btn-sm border-0 px-3" type="submit">Comment</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!--Delete listing-->
{% if check %}
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <a class="btn btn-sm btn-primary" type="button" href="{% url 'auctions:delete' item.id %}" >Delete listing</a>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}


auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="dropdown">
            <h1 class="float-left">Auction</h1>
            <button class="btn btn-secondary dropdown-toggle float-right" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.is_authenticated %}
                Hello, <strong>{{ user.username }}</strong>
                {% else %}
                Not signed in  
                {% endif %}
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'auctions:myitems' %}">My Listings</a>
                <a class="dropdown-item" href="{% url 'auctions:logout' %}">Log Out</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'auctions:login' %}?next={{ request.path }}">Log In</a>
                <a class="dropdown-item" href="{% url 'auctions:register' %}">Register</a>
                {% endif %}
            </div>
        </div><br><br>
        <hr>
        <div class="container-fluid">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
            </li>
            <div class="dropdown">
                <button class="btn dropdown-toggle float-right" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: rgb(52, 138, 236);">
                    Categories
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'auctions:category' 'antiques' %}">Antiques</a>
                    <a class="dropdown-item" href="{% url 'auctions:category' 'books' %}">Books</a>
                    <a class="dropdown-item" href="{% url 'auctions:category' 'crafts' %}">Crafts</a>
                    <a class="dropdown-item" href="{% url 'auctions:category' 'electronics' %}">Electronics</a>
                    <a class="dropdown-item" href="{% url 'auctions:category' 'jewellery' %}">Jewellery</a>
                    <a class="dropdown-item" href="{% url 'auctions:category' 'paintings' %}">Paintings</a>
                </div>
            </div>
            {% endif %}
        </ul>
        </div>
        <hr>
        {% block body %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-6">
            <h2>Login</h2>

            {% if message %}
                <div>{{ message }}</div>
            {% endif %}

            <form action="{% url 'auctions:login' %}?next={{ request.GET.next }}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.username.label }}{{ form.username }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}{{ form.password }}
                </div>
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Login">
                </div>
            </form>

            Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>
        </div>
    </div>
</div>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.username.label }}{{ form.username }}
        </div>
        <div class="form-group">
            {{ form.email.label }}{{ form.email }}
        </div>
        <div class="form-group">
            {{ form.password.label }}{{ form.password }}
        </div>
        <div class="form-group">
            {{ form.confirmation.label }}{{ form.confirmation }}
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}